### ISSUE TITLE
please add some features

### ISSUE THREAD

**Issue by phanousk** [ivsero/rt-dumper#1]
Hi,
I like this program and want to use it more often. For this I need some changes:
- could you please add https support?
- could you please add a parameter for exact ticket ID extraction?

On top of that, would it be possible to make an opposite script for importing such exported ticket through REST API to another RT instance?

Thank you, Petr

**Comment by ivsero** [comment]
Hello.
Now you can specify schema (http or https) in --schema parameter. For example:
`--schema https`
Also I added --ticket parameter. You can specify ticket id for downloading data of a single ticket:
`--ticket 1`.
Thank you for feedback! :)

**Comment by ivsero** [comment]
> On top of that, would it be possible to make an opposite script for importing such exported ticket through REST API to another RT instance?

I think about this functionality. Perhaps it will be implemented later.

**Comment by phanousk** [comment]
Great, thank you!
